project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "qmd/*.qmd"
  

website:
  title: "Analyse Statistique des Profils GitHub Influents"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Projet Principal
        contents:
          - qmd/01-analyse-profiles-github.qmd
          - qmd/02-presentation-profiles-github.qmd
          
      - section: Analyses Suppl√©mentaires
      
format:
  html:
    theme: cosmo
    css: thpe.css
    toc: true
    number-sections: true
    #embed-resources: true
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
    papersize: a4
    geometry:
      - top=20mm
      - left=25mm
      - bottom=25mm
bibliography: bib.bib
csl: apa.csl

execute:
  freeze: auto